### ISSUE TITLE
Release for transformers upperbound

### ISSUE THREAD

**Issue by timmytofu** [ozataman/snap-extras#13]
The transformers upperbound was bumped to < 0.5 in 910eb324 in May 2014, but the latest version on Hackage still has < 0.4 - could you release a version with this upperbound increased?

**Comment by timmytofu** [comment]
Oh, well, snap-core is in the same state (bumped but not released), so I guess there's no hurry anyways.

**Comment by mightybyte** [comment]
Actually, snap-core does not depend on transformers.  So yeah, we should release a new version.

**Comment by mightybyte** [comment]
This was taken care of awhile ago.
