### ISSUE TITLE
snap-extra-0.12.0.0 not compatible w/ base < 4.8

### ISSUE THREAD

**Issue by hvr** [ozataman/snap-extras#21]
because `Prelude` only started exporting `Monoid(..)` w/ base-4.8;
I've already fixed up the meta-data at https://hackage.haskell.org/package/snap-extras-0.12.0.0/revisions/

```
Configuring library for snap-extras-0.12.0.0..
Preprocessing library for snap-extras-0.12.0.0..
Building library for snap-extras-0.12.0.0..
[ 1 of 16] Compiling Snap.Extras.SpliceUtils.Common ( src/Snap/Extras/SpliceUtils/Common.hs, /tmp/matrix-worker/1501820448/dist-newstyle/build/x86_64-linux/ghc-7.8.4/snap-extras-0.12.0.0/build/Snap/Extras/SpliceUtils/Common.o )
[ 2 of 16] Compiling Snap.Extras.NavTrails ( src/Snap/Extras/NavTrails.hs, /tmp/matrix-worker/1501820448/dist-newstyle/build/x86_64-linux/ghc-7.8.4/snap-extras-0.12.0.0/build/Snap/Extras/NavTrails.o )
[ 3 of 16] Compiling Paths_snap_extras ( /tmp/matrix-worker/1501820448/dist-newstyle/build/x86_64-linux/ghc-7.8.4/snap-extras-0.12.0.0/build/autogen/Paths_snap_extras.hs, /tmp/matrix-worker/1501820448/dist-newstyle/build/x86_64-linux/ghc-7.8.4/snap-extras-0.12.0.0/build/Paths_snap_extras.o )
[ 4 of 16] Compiling Snap.Extras.SpliceUtils.Interpreted ( src/Snap/Extras/SpliceUtils/Interpreted.hs, /tmp/matrix-worker/1501820448/dist-newstyle/build/x86_64-linux/ghc-7.8.4/snap-extras-0.12.0.0/build/Snap/Extras/SpliceUtils/Interpreted.o )
[ 5 of 16] Compiling Snap.Extras.SpliceUtils.Compiled ( src/Snap/Extras/SpliceUtils/Compiled.hs, /tmp/matrix-worker/1501820448/dist-newstyle/build/x86_64-linux/ghc-7.8.4/snap-extras-0.12.0.0/build/Snap/Extras/SpliceUtils/Compiled.o )
[ 6 of 16] Compiling Snap.Extras.TextUtils ( src/Snap/Extras/TextUtils.hs, /tmp/matrix-worker/1501820448/dist-newstyle/build/x86_64-linux/ghc-7.8.4/snap-extras-0.12.0.0/build/Snap/Extras/TextUtils.o )
[ 7 of 16] Compiling Snap.Extras.Tabs ( src/Snap/Extras/Tabs.hs, /tmp/matrix-worker/1501820448/dist-newstyle/build/x86_64-linux/ghc-7.8.4/snap-extras-0.12.0.0/build/Snap/Extras/Tabs.o )

src/Snap/Extras/Tabs.hs:51:19:
    Not in scope: ‘mempty’
    Perhaps you meant one of these:
      ‘T.empty’ (imported from Data.Text),
      ‘_Empty’ (imported from Control.Lens)

src/Snap/Extras/Tabs.hs:68:56:
    Not in scope: ‘mempty’
    Perhaps you meant one of these:
      ‘T.empty’ (imported from Data.Text),
      ‘_Empty’ (imported from Control.Lens)
``

**Comment by MichaelXavier** [comment]
@hvr As mentioned in the above commit, I don't really have a good setup for testing versions of base that old but with new enough versions of other dependencies. It seemed like the solution is to implicitly import mempty from monoid so I went through the modules that used mempty and did that. I think this satisfies old base and prevents warnings in newer base, though this project is not yet warning free.

Can you give the `21-old-base` branch a spin and let me know if that works in your setup? If so, I will try to get the build cleaned up and cut a release.

**Comment by hvr** [comment]
I was able to build that branch w/ GHC 7.8, 7.6 and 7.4; 

Btw, as you may know, testing a wide range of dependencies & GHCs is what I created https://github.com/hvr/multi-ghc-travis for. If you're interested, I'm happy to send you a PR...

**Comment by MichaelXavier** [comment]
I've used that in the past. I usually stick to just testing with stack as a lot of users are using that (including me) and the resulting .travis.yml is really simple to understand.

I've merged the branch. I'll take a look at fixing the long-broken travis build and will cut a C release sometime soon.

**Comment by hvr** [comment]
Fair enough. <rant>Unfortunately, testing only with Stack hides a lot of issues (by design, as Stack reduces coverage to a very small vetted configuration space of packages; and even the nightly snapshot often lags behind Hackage for several weeks or even months in picking up current versions of dependencies), which makes it rather ineffective for CI purposes.</rant>

I hope I'll be able to simplify the generated `.travis.yml`. 

Which part of e.g. https://github.com/haskell/parsec/blob/master/.travis.yml do you consider most difficult to understand?

**Comment by MichaelXavier** [comment]
I guess I haven't looked in a while. It is superficially more complex than the .travis.yml files I write. Maybe my bigger resistance is that for development I use stack because I don't want to spend a bunch of my time fighting with the dependency resolver, rigging local GHC version switchers, etc. So having to do this with CI where build times are even slower and harder to debug would definitely sap the energy I make available to do open source. So if most of my users are going to use stack and I'm going to use stack, it makes sense for me to target a range of LTSes and nightlies than using trying to get things to resolve under cabal directly.
